"""Remove confirmed_at

Revision ID: b8daf1363bdd
Revises: 0a8fc485cd19
Create Date: 2023-12-07 12:58:54.088186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8daf1363bdd'
down_revision = '0a8fc485cd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
