"""empty message

Revision ID: d17596694f48
Revises: 
Create Date: 2023-12-18 16:37:46.984174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17596694f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=80), nullable=True),
    sa.Column('device', sa.VARCHAR(length=200), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('unique_fs_uniquifier_constraint', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('unique_fs_uniquifier_constraint')
    )
    # ### end Alembic commands ###
