# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FLASK_APP: app
      FLASK_ENV: development
      SECRET_KEY: Y0ur_cOmpany_Secr3T_K3y_D0_N0t_5har3
      SECURITY_PASSWORD_SALT: Sal7_F0r_YoUr_CoMpAnY_PaS5w0rD
      SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install libldap2-dev and libsasl2-dev
      run: sudo apt-get install -y libldap2-dev libsasl2-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the script
      run: python create_tables.py
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
